import { Button } from "@/components/ui/button";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { type Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex w-full min-h-screen flex-col items-center justify-center py-10`}
        >
          <SignedOut>
            <Button asChild className="mb-3 w-40" size={"lg"}>
              <SignInButton />
            </Button>
            <Button asChild variant={"outline"} className="w-40" size={"lg"}>
              <SignUpButton />
            </Button>
          </SignedOut>
          <SignedIn>
            <div className="mb-4 border px-5 py-2 rounded-2xl">
              <UserButton showName />
            </div>
            <div className="max-w-xl">{children}</div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
